---
- hosts: localhost
  connection: local
  become: true

  tasks:
  # - name: Show facts available on the system
  #   debug:
  #     var: ansible_facts

  - name: add cran repo key
    get_url:
      url: 'https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc'
      dest: '/etc/apt/keyrings/cran_ubuntu_key.asc'
    when: cran is defined and cran != ''

  - name: add cran repo url
    apt_repository:
      repo: 'deb [signed-by=/etc/apt/keyrings/cran_ubuntu_key.asc] https://cloud.r-project.org/bin/linux/ubuntu {{ansible_facts.distribution_release}}-cran40/'
      state: present
    when: cran is defined and cran != ''

  - name: update installed packages
    apt:
      name: "*"
      state: latest
      update_cache: true

  - name: install packages
    apt:
      pkg:
        - build-essential
        - fonts-jetbrains-mono
        - fonts-jetbrains-mono-web
        - fonts-cascadia-code
        - fonts-firacode
        - git
        - gh
        - cmake
        - ccache
        - meson
        - curl
        - wget
        - jq
        - gnuplot
        - ttyplot
        - graphviz
        - r-base
        - r-base-dev
        - libopenblas-dev
        - pandoc
        - libxml2-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - libx11-dev
        - libglu1-mesa-dev
        - libftgl-dev
        - libfontconfig1-dev
        - libcairo2-dev
        - libgsl-dev
        - libudunits2-dev
        - libgdal-dev
        - libmpfr-dev
        - libgmp-dev
        - libharfbuzz-dev
        - libfribidi-dev
        - libv8-dev
        - libunwind-dev
        - libarchive-dev
        - libsodium-dev
        - libsecret-1-dev
        - libgit2-dev
        - libmagick++-dev
        - libpoppler-cpp-dev
        - libavfilter-dev
        - unixodbc-dev
        - tdsodbc
        - python3-venv
        - python3-virtualenv
        - gnucobol
        - hexyl
        - bvi
        - vim
        - sqlite3
        - sqlite3-tools
        - tmux
        - multitail
        - ispell
        - ripgrep
        - fd-find
        - fzf
        - bat
        - eza
        - tree
        - gdu
        - neofetch
        - cpufetch
        - figlet
        - dos2unix
        - htop
        - btop
        - nvtop
        - inxi
        - mtr-tiny
      state: present
      update_cache: true

  - name: install snaps
    snap:
      name:
        - docker
        - ruff
        - pylsp

  - name: install classic snaps
    snap:
      classic: yes
      name:
        - helix
        - go
        - powershell
        - astral-uv
        - node

  - name: install duckdb cli
    unarchive:
      src: https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
      dest: /usr/local/bin
      remote_src: yes
