---
- hosts: localhost
  connection: local
  become: true

  tasks:
  # - name: Show facts available on the system
  #   debug:
  #     var: ansible_facts

  - name: add cran repo key
    get_url:
      url: 'https://cloud.r-project.org/bin/linux/ubuntu/marutter_pubkey.asc'
      dest: '/etc/apt/keyrings/cran_ubuntu_key.asc'
      # checksum: 'sha256:E298A3A825C0D65DFD57CBB651716619E084DAB9'

  - name: add cran repo url
    apt_repository:
      repo: 'deb [signed-by=/etc/apt/keyrings/cran_ubuntu_key.asc] https://cloud.r-project.org/bin/linux/ubuntu {{ansible_facts.distribution_release}}-cran40/'
      state: present

  - name: update installed packages
    apt:
      name: "*"
      state: latest
      update_cache: true

  - name: install generic packages
    apt:
      pkg:
        - docker.io
        - docker-buildx
        - docker-compose-v2
        - build-essential
        - fonts-cascadia-code
        - fonts-firacode
        - git
        - cmake
        - ccache
        - curl
        - wget
        - gnuplot
        - graphviz
        - r-base
        - r-base-dev
        - libxml2-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - libx11-dev
        - libglu1-mesa-dev
        - libftgl-dev
        - libfontconfig1-dev
        - libcairo2-dev
        - libgsl-dev
        - libudunits2-dev
        - libgdal-dev
        - libmpfr-dev
        - libgmp-dev
        - libharfbuzz-dev
        - libfribidi-dev
        - libv8-dev
        - libunwind-dev
        - libarchive-dev
        - unixodbc-dev
        - tdsodbc
        - python3-virtualenv
        - rust-all
        - gnucobol
        - hexyl
        - bvi
        - vim
        - sloccount
        - tmux
        - multitail
        - ispell
        - ripgrep
        - fd-find
        - fzf
        - gdu
        - neofetch
        - cpufetch
        - figlet
        - dos2unix
        - btop
        - htop
        - nvtop
      state: present

  - name: add user to groups
    user:
      name: "{{ host_user }}"
      groups:
        - docker
      append: yes
