---
- hosts: localhost
  connection: local
  become: true

  tasks:
#  - name: Show facts available on the system
#    debug:
#      var: ansible_facts

  - name: update installed packages
    apt:
      name: "*"
      state: latest
      update_cache: true

  - name: install debian packages
    apt:
      pkg:
        - snapd
      state: present
    when: ansible_facts['distribution'] == 'Debian'

  - name: install ubuntu packages
    apt:
      pkg:
        - ubuntu-restricted-extras
      state: present
    when: ansible_facts['distribution'] == 'Ubuntu'

  - name: install generic packages
    apt:
      pkg:
        - build-essential
        - git
        - curl
        - wget
        - python3
        - python3-pip
        - python3-setuptools
        - python3-wheel
        - python3-venv
        - python3-virtualenv
        - r-base
        - r-base-dev
        - docker.io
        - docker-compose
        - vim
        - ripgrep
        - fd-find
        - fzf
        - figlet
        - dos2unix
        - texlive-full
        - btop
        - htop
        - nvtop
      state: present

  - name: autoremove packages
    apt:
      autoremove: yes

  - name: autoclean packages
    apt:
      autoclean: yes

  - name: add user to groups
    user:
      name: "{{ host_user }}"
      groups:
        - docker
      append: yes
