---
- hosts: localhost
  connection: local
  become: true

  tasks:
  # - name: Show facts available on the system
  #   debug:
  #     var: ansible_facts

  - name: update installed packages
    apt:
      name: "*"
      state: latest
      update_cache: true

  - name: install packages
    apt:
      pkg:
        - linux-tools-common
        - docker.io
        - docker-buildx
        - docker-compose-v2
        - build-essential
        - fonts-cascadia-code
        - fonts-firacode
        - git
        - gh
        - cmake
        - ccache
        - meson
        - curl
        - wget
        - jq
        - gnuplot
        - ttyplot
        - graphviz
        - r-base
        - r-base-dev
        - libopenblas-dev
        - pandoc
        - libxml2-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - libx11-dev
        - libglu1-mesa-dev
        - libftgl-dev
        - libfontconfig1-dev
        - libcairo2-dev
        - libgsl-dev
        - libudunits2-dev
        - libgdal-dev
        - libmpfr-dev
        - libgmp-dev
        - libharfbuzz-dev
        - libfribidi-dev
        - libv8-dev
        - libunwind-dev
        - libarchive-dev
        - libsodium-dev
        - libsecret-1-dev
        - libgit2-dev
        - libmagick++-dev
        - libpoppler-cpp-dev
        - libavfilter-dev
        - unixodbc-dev
        - tdsodbc
        - python3-venv
        - python3-virtualenv
        - nodejs
        - npm
        - rust-all
        - gnucobol
        - hexyl
        - bvi
        - vim
        - sqlite3
        - sqlite3-tools
        - sqlite3-doc
        - multitail
        - ispell
        - ripgrep
        - fd-find
        - fzf
        - tree
        - gdu
        - neofetch
        - cpufetch
        - figlet
        - dos2unix
        - btop
        - nvtop
      state: present
      update_cache: true

  - name: install classic snaps
    snap:
      classic: yes
      name:
        - go
        - powershell

  - name: install duckdb cli
    unarchive:
      src: https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
      dest: /usr/local/bin
      remote_src: yes

  - name: add user to groups
    user:
      name: "{{ host_user }}"
      groups:
        - docker
      append: yes
    when: host_user is defined and host_user != ''
