---
- hosts: localhost
  connection: local
  become: true

  tasks:
#  - name: Show facts available on the system
#    debug:
#      var: ansible_facts

  - name: update installed packages
    apt:
      name: "*"
      state: latest
      update_cache: true

  - name: install generic packages
    apt:
      pkg:
        - build-essential
        - emscripten
        - fonts-firacode
        - fonts-jetbrains-mono
        - fonts-3270
        - fonts-anonymous-pro
        - fonts-proggy
        - fonts-inconsolata
        - fonts-hack
        - git
        - cmake
        - ccache
        - curl
        - wget
        - r-base
        - r-base-dev
        - libxml2-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - libx11-dev
        - libglu1-mesa-dev
        - libftgl-dev
        - libfontconfig1-dev
        - libcairo2-dev
        - libgsl-dev
        - libudunits2-dev
        - libgdal-dev
        - libmpfr-dev
        - libgmp-dev
        - libharfbuzz-dev
        - libfribidi-dev
        - libv8-dev
        - libunwind-dev
        - libarchive-dev
        - python3-virtualenv
        - rust-all
        - gnucobol
        - hexyl
        - bvi
        - gnuplot
        - docker.io
        - vim
        - emacs
        - elpa-ess
        - tmux
        - multitail
        - recutils
        - ispell
        - ripgrep
        - fd-find
        - fzf
        - exa
        - gdu
        - ncdu
        - ranger
        - mc
        - rmlint
        - stow
        - neofetch
        - cpufetch
        - sloccount
        - figlet
        - graphviz
        - texlive-full
        - poppler-utils
        - html2text
        - dos2unix
        - btop
        - htop
        - glances
      state: present

  - name: install debian packages
    apt:
      pkg:
        - snapd
        - docker-compose
      state: present
    when: ansible_facts['distribution'] == 'Debian'

  - name: install debian megasync
    apt:
      deb: https://mega.nz/linux/repo/{{ ansible_distribution }}_{{ ansible_distribution_version }}/amd64/megasync-{{ ansible_distribution }}_{{ ansible_distribution_version }}_amd64.deb
      state: present
    when: ansible_facts['distribution'] == 'Debian'

  - name: install ubuntu packages
    apt:
      pkg:
        - fonts-cascadia-code
        - docker-buildx
        - docker-compose-v2
        - nvtop
      state: present
    when: ansible_facts['distribution'] == 'Ubuntu'

  - name: install ubuntu megasync
    apt:
      deb: https://mega.nz/linux/repo/x{{ ansible_distribution }}_{{ ansible_distribution_version }}/amd64/megasync-x{{ ansible_distribution }}_{{ ansible_distribution_version }}_amd64.deb
      state: present
    when: ansible_facts['distribution'] == 'Ubuntu'

  - name: install rstudio desktop
    apt:
      deb: https://download1.rstudio.org/electron/jammy/amd64/rstudio-2023.12.1-402-amd64.deb
      state: present

  - name: install shiny server
    apt:
      deb: https://download3.rstudio.org/ubuntu-18.04/x86_64/shiny-server-1.5.21.1012-amd64.deb
      state: present

  - name: autoremove packages
    apt:
      autoremove: yes

  - name: autoclean packages
    apt:
      autoclean: yes

  - name: add user to groups
    user:
      name: "{{ host_user }}"
      groups:
        - docker
      append: yes
