---
- hosts: localhost
  connection: local
  become: true

  tasks:
  # - name: Show facts available on the system
  #   debug:
  #     var: ansible_facts

  - name: install packages
    ansible.builtin.package:
      name:
        - build-essential
        - emscripten
        - docker.io
        - docker-buildx
        - docker-compose-v2
        - git
        - gh
        - cmake
        - ccache
        - meson
        - curl
        - wget
        - jq
        - gnuplot
        - ttyplot
        - graphviz
        - r-base
        - r-base-dev
        - libopenblas-dev
        - pandoc
        - libxml2-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - libx11-dev
        - libglu1-mesa-dev
        - libftgl-dev
        - libfontconfig1-dev
        - libcairo2-dev
        - libgsl-dev
        - libudunits2-dev
        - libgdal-dev
        - libmpfr-dev
        - libgmp-dev
        - libharfbuzz-dev
        - libfribidi-dev
        - libv8-dev
        - libunwind-dev
        - libarchive-dev
        - libsodium-dev
        - libsecret-1-dev
        - libgit2-dev
        - libmagick++-dev
        - libpoppler-cpp-dev
        - libavfilter-dev
        - unixodbc-dev
        - tdsodbc
        - python3-venv
        - python3-virtualenv
        - golang
        - nodejs
        - npm
        - gnucobol
        - hexyl
        - bvi
        - vim
        - sqlite3
        - sqlite3-tools
        - tmux
        - multitail
        - ispell
        - ripgrep
        - fd-find
        - fzf
        - bat
        - eza
        - tree
        - gdu
        - neofetch
        - cpufetch
        - figlet
        - dos2unix
        - htop
        - btop
        - nvtop
        - inxi
        - mtr-tiny
      state: present
      update_cache: true

  - name: install duckdb cli
    ansible.builtin.unarchive:
      src: https://github.com/duckdb/duckdb/releases/latest/download/duckdb_cli-linux-amd64.zip
      dest: /usr/local/bin
      remote_src: yes
