---
- hosts: localhost
  connection: local
  become: true

  tasks:
#  - name: Show facts available on the system
#    debug:
#      var: ansible_facts

  - name: update installed packages
    apt:
      name: "*"
      state: latest
      update_cache: true

  - name: install debian packages
    apt:
      pkg:
        - snapd
      state: present
    when: ansible_facts['distribution'] == 'Debian'

  - name: install ubuntu packages
    apt:
      pkg:
        - ubuntu-restricted-extras
      state: present
    when: ansible_facts['distribution'] == 'Ubuntu'

  - name: install generic packages
    apt:
      pkg:
        - build-essential
        - fonts-jetbrains-mono
        - git
        - cmake
        - curl
        - wget
        - r-base
        - r-base-dev
        - libxml2-dev
        - libcurl4-openssl-dev
        - libssl-dev
        - libx11-dev
        - libglu1-mesa-dev
        - libftgl-dev
        - libfontconfig1-dev
        - libcairo2-dev
        - libgsl-dev
        - libudunits2-dev
        - libgdal-dev
        - libmpfr-dev
        - libgmp-dev
        - python3-virtualenv
        - rust-all
        - golang
        - docker.io
        - docker-compose
        - vim
        - emacs
        - elpa-ess
        - elpa-graphviz-dot-mode
        - elpa-company
        - elpa-htmlize
        - elpa-csv-mode
        - elpa-yaml-mode
        - ripgrep
        - fd-find
        - fzf
        - figlet
        - graphviz
        - graphviz-doc
        - texlive-full
        - dos2unix
        - btop
        - nvtop
        - glances
      state: present

  - name: autoremove packages
    apt:
      autoremove: yes

  - name: autoclean packages
    apt:
      autoclean: yes

  - name: add user to groups
    user:
      name: "{{ host_user }}"
      groups:
        - docker
      append: yes
